import com.toedter.calendar.JDateChooser;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import static java.awt.Font.BOLD;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
public class addFlight extends JInternalFrame {

  /** Creates new form addFlight */
  public addFlight() {
    initComponents();
    autoID();
  }

  Connection con;
  PreparedStatement pst;

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  private void initComponents() {

    jPanel1 = new JPanel();
    jLabel1 = new JLabel();
    txtflightid = new JLabel();
    jLabel3 = new JLabel();
    jLabel4 = new JLabel();
    jLabel5 = new JLabel();
    txtflightname = new JTextField();
    jLabel6 = new JLabel();
    txtdate = new JDateChooser();
    jLabel7 = new JLabel();
    txtdtime = new JTextField();
    txtarrtime = new JTextField();
    jLabel8 = new JLabel();
    jLabel9 = new JLabel();
    txtflightcharge = new JTextField();
    jButton1 = new JButton();
    jButton2 = new JButton();
    txtsource = new JComboBox<>();
    txtdepart = new JComboBox<>();

    jPanel1.setBackground(new Color(51, 51, 255));

    jLabel1.setFont(new Font("Tahoma", BOLD, 11)); // NOI18N
    jLabel1.setForeground(new Color(255, 255, 255));
    jLabel1.setText("Flight ID");

    txtflightid.setFont(new Font("Tahoma", BOLD, 12)); // NOI18N
    txtflightid.setForeground(new Color(255, 255, 0));
    txtflightid.setText("jLabel2");

    jLabel3.setFont(new Font("Tahoma", BOLD, 11)); // NOI18N
    jLabel3.setForeground(new Color(255, 255, 255));
    jLabel3.setText("Flight Name");

    jLabel4.setFont(new Font("Tahoma", BOLD, 11)); // NOI18N
    jLabel4.setForeground(new Color(255, 255, 255));
    jLabel4.setText("Source");

    jLabel5.setFont(new Font("Tahoma", BOLD, 11)); // NOI18N
    jLabel5.setForeground(new Color(255, 255, 255));
    jLabel5.setText("Departure");

    jLabel6.setForeground(new Color(255, 255, 255));
    jLabel6.setText("Date");

    jLabel7.setForeground(new Color(255, 255, 255));
    jLabel7.setText("Depart Time");

    jLabel8.setForeground(new Color(255, 255, 255));
    jLabel8.setText("Arrive Time");

    jLabel9.setForeground(new Color(255, 255, 255));
    jLabel9.setText("Flight Charge");

    jButton1.setText("Add");
    jButton1.addActionListener(this::jButton1ActionPerformed);

    jButton2.setText("Cancel");
    jButton2.addActionListener(this::jButton2ActionPerformed);

    txtsource.setModel(
        new DefaultComboBoxModel<>(
            new String[] {"India\t", "Srilanka", "UK", "USA", "Canada", "China"}));

    txtdepart.setModel(
        new DefaultComboBoxModel<>(
            new String[] {"India\t", "Srilanka", "UK", "USA", "Canada", "China"}));

    GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel1Layout
                    .createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addGroup(
                                jPanel1Layout
                                    .createSequentialGroup()
                                    .addGroup(
                                        jPanel1Layout
                                            .createParallelGroup(GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3))
                                    .addGroup(
                                        jPanel1Layout
                                            .createParallelGroup(GroupLayout.Alignment.LEADING)
                                            .addGroup(
                                                jPanel1Layout
                                                    .createSequentialGroup()
                                                    .addGap(38, 38, 38)
                                                    .addComponent(txtflightid))
                                            .addGroup(
                                                jPanel1Layout
                                                    .createSequentialGroup()
                                                    .addGap(28, 28, 28)
                                                    .addComponent(
                                                        txtflightname,
                                                        GroupLayout.PREFERRED_SIZE,
                                                        136,
                                                        GroupLayout.PREFERRED_SIZE))))
                            .addGroup(
                                GroupLayout.Alignment.TRAILING,
                                jPanel1Layout
                                    .createSequentialGroup()
                                    .addGroup(
                                        jPanel1Layout
                                            .createParallelGroup(GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                    .addPreferredGap(
                                        LayoutStyle.ComponentPlacement.RELATED,
                                        GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                    .addGroup(
                                        jPanel1Layout
                                            .createParallelGroup(
                                                GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtsource, 0, 136, Short.MAX_VALUE)
                                            .addComponent(
                                                txtdepart,
                                                0,
                                                GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE))))
                    .addGap(103, 103, 103)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(
                                jPanel1Layout
                                    .createSequentialGroup()
                                    .addGroup(
                                        jPanel1Layout
                                            .createParallelGroup(GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                    .addGap(62, 62, 62)
                                    .addGroup(
                                        jPanel1Layout
                                            .createParallelGroup(
                                                GroupLayout.Alignment.LEADING, false)
                                            .addComponent(
                                                txtdate,
                                                GroupLayout.DEFAULT_SIZE,
                                                174,
                                                Short.MAX_VALUE)
                                            .addComponent(txtdtime)
                                            .addComponent(txtarrtime)))
                            .addGroup(
                                jPanel1Layout
                                    .createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(52, 52, 52)
                                    .addComponent(
                                        txtflightcharge,
                                        GroupLayout.PREFERRED_SIZE,
                                        172,
                                        GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(
                GroupLayout.Alignment.TRAILING,
                jPanel1Layout
                    .createSequentialGroup()
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(
                        jButton1, GroupLayout.PREFERRED_SIZE, 117, GroupLayout.PREFERRED_SIZE)
                    .addGap(29, 29, 29)
                    .addComponent(
                        jButton2, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)
                    .addGap(39, 39, 39)));
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel1Layout
                    .createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addGroup(
                                jPanel1Layout
                                    .createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtflightid)
                                    .addComponent(jLabel6))
                            .addComponent(
                                txtdate,
                                GroupLayout.PREFERRED_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(
                                txtflightname,
                                GroupLayout.PREFERRED_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(
                                txtdtime,
                                GroupLayout.PREFERRED_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE))
                    .addGap(28, 28, 28)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(
                                txtarrtime,
                                GroupLayout.PREFERRED_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(
                                txtsource,
                                GroupLayout.PREFERRED_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE))
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(
                                jPanel1Layout
                                    .createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addGroup(
                                        jPanel1Layout
                                            .createParallelGroup(GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(
                                                txtdepart,
                                                GroupLayout.PREFERRED_SIZE,
                                                GroupLayout.DEFAULT_SIZE,
                                                GroupLayout.PREFERRED_SIZE)))
                            .addGroup(
                                jPanel1Layout
                                    .createSequentialGroup()
                                    .addGap(34, 34, 34)
                                    .addGroup(
                                        jPanel1Layout
                                            .createParallelGroup(GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel9)
                                            .addComponent(
                                                txtflightcharge,
                                                GroupLayout.PREFERRED_SIZE,
                                                GroupLayout.DEFAULT_SIZE,
                                                GroupLayout.PREFERRED_SIZE))))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(
                                jButton1,
                                GroupLayout.PREFERRED_SIZE,
                                46,
                                GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                jButton2,
                                GroupLayout.PREFERRED_SIZE,
                                46,
                                GroupLayout.PREFERRED_SIZE))
                    .addGap(43, 43, 43)));

    GroupLayout layout = new GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(
                        jPanel1,
                        GroupLayout.PREFERRED_SIZE,
                        GroupLayout.DEFAULT_SIZE,
                        GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(22, Short.MAX_VALUE)));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(
                GroupLayout.Alignment.TRAILING,
                layout
                    .createSequentialGroup()
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(
                        jPanel1,
                        GroupLayout.PREFERRED_SIZE,
                        GroupLayout.DEFAULT_SIZE,
                        GroupLayout.PREFERRED_SIZE)
                    .addGap(39, 39, 39)));

    pack();
  }

  public void autoID() {
    try {
      Class.forName("com.mysql.cj.jdbc.Driver");
      con = DriverManager.getConnection("jdbc:mysql://localhost/airline", "root", "password");
      Statement s = con.createStatement();
      ResultSet rs = s.executeQuery("SELECT MAX(ID) FROM FLIGHT");
      rs.next();
      rs.getString("MAX(ID)");
      if (rs.getString("MAX(ID)") == null) {
        txtflightid.setText("FO001");
      } else {
        long id = Long.parseLong(rs.getString("MAX(ID)").substring(2));
        id++;
        txtflightid.setText("FO" + String.format("%03d", id));
      }

    } catch (ClassNotFoundException | SQLException ex) {
      Logger.getLogger(addCustomer.class.getName()).log(Level.SEVERE, null, ex);
    }
  }

  private void jButton1ActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:

    String id = txtflightid.getText();
    String flightname = txtflightname.getText();

    String source = Objects.requireNonNull(txtsource.getSelectedItem()).toString().trim();
    String depart = Objects.requireNonNull(txtdepart.getSelectedItem()).toString().trim();

    DateFormat da = new SimpleDateFormat("yyyy-MM-dd");
    String date = da.format(txtdate.getDate());

    String departtime = txtdtime.getText();
    String arrtime = txtarrtime.getText();
    String flightcharge = txtflightcharge.getText();

    try {
      Class.forName("com.mysql.cj.jdbc.Driver");
      con = DriverManager.getConnection("jdbc:mysql://localhost/airline", "root", "password");
      pst =
          con.prepareStatement(
              "INSERT INTO FLIGHT(ID, flightName, source, depart, date, departTime, arriveTime, flightCharge) VALUES (?, ?, ?, ?, ?, ?, ?, ?)");

      pst.setString(1, id);
      pst.setString(2, flightname);
      pst.setString(3, source);
      pst.setString(4, depart);
      pst.setString(5, date);
      pst.setString(6, departtime);
      pst.setString(7, arrtime);
      pst.setString(8, flightcharge);

      pst.executeUpdate();

      JOptionPane.showMessageDialog(null, "Flight Created.........");
    } catch (ClassNotFoundException | SQLException ex) {
      Logger.getLogger(addFlight.class.getName()).log(Level.SEVERE, null, ex);
    }
  }

  private void jButton2ActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:
    this.hide();
  }

  // Variables declaration - do not modify //
  private JButton jButton1;
  private JButton jButton2;
  private JLabel jLabel1;
  private JLabel jLabel3;
  private JLabel jLabel4;
  private JLabel jLabel5;
  private JLabel jLabel6;
  private JLabel jLabel7;
  private JLabel jLabel8;
  private JLabel jLabel9;
  private JPanel jPanel1;
  private JTextField txtarrtime;
  private JDateChooser txtdate;
  private JComboBox<String> txtdepart;
  private JTextField txtdtime;
  private JTextField txtflightcharge;
  private JLabel txtflightid;
  private JTextField txtflightname;
  private JComboBox<String> txtsource;
  // End of variables declaration //
}
