import com.toedter.calendar.JDateChooser;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

import static java.awt.Font.BOLD;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class addFlight extends JInternalFrame {

  /** Creates new form add flight */
  public addFlight() {
    initComponents();
    autoID();
  }

  Connection connection;
  PreparedStatement preparedStatement;

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  // <editor-fold default state="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    JPanel jPanel1 = new JPanel();
    JLabel jLabel1 = new JLabel();
    txtFlightID = new JLabel();
    JLabel jLabel3 = new JLabel();
    JLabel jLabel4 = new JLabel();
    JLabel jLabel5 = new JLabel();
    txtFlightName = new JTextField();
    JLabel jLabel6 = new JLabel();
    txtDate = new JDateChooser();
    JLabel jLabel7 = new JLabel();
    txtTime = new JTextField();
    txtArriveTime = new JTextField();
    JLabel jLabel8 = new JLabel();
    JLabel jLabel9 = new JLabel();
    txtFlightCharge = new JTextField();
    JButton jButton1 = new JButton();
    JButton jButton2 = new JButton();
    txtSource = new JComboBox<>();
    txtDepart = new JComboBox<>();

    jPanel1.setBackground(new Color(51, 51, 255));

    jLabel1.setFont(new Font("Tahoma", BOLD, 11)); // NOI18N
    jLabel1.setForeground(new Color(255, 255, 255));
    jLabel1.setText("Flight ID");

    txtFlightID.setFont(new Font("Tahoma", BOLD, 12)); // NOI18N
    txtFlightID.setForeground(new Color(255, 255, 0));
    txtFlightID.setText("jLabel2");

    jLabel3.setFont(new Font("Tahoma", BOLD, 11)); // NOI18N
    jLabel3.setForeground(new Color(255, 255, 255));
    jLabel3.setText("Flight Name");

    jLabel4.setFont(new Font("Tahoma", BOLD, 11)); // NOI18N
    jLabel4.setForeground(new Color(255, 255, 255));
    jLabel4.setText("Source");

    jLabel5.setFont(new Font("Tahoma", BOLD, 11)); // NOI18N
    jLabel5.setForeground(new Color(255, 255, 255));
    jLabel5.setText("Departure");

    jLabel6.setForeground(new Color(255, 255, 255));
    jLabel6.setText("Date");

    jLabel7.setForeground(new Color(255, 255, 255));
    jLabel7.setText("Depart Time");

    jLabel8.setForeground(new Color(255, 255, 255));
    jLabel8.setText("Arrival Time");

    jLabel9.setForeground(new Color(255, 255, 255));
    jLabel9.setText("Flight Charge");

    jButton1.setText("Add");
    jButton1.addActionListener(this::jButton1ActionPerformed);

    jButton2.setText("Cancel");
    jButton2.addActionListener(this::jButton2ActionPerformed);

    txtSource.setModel(
        new DefaultComboBoxModel<>(
            new String[] {"India\t", "Srilanka", "Uk", "Usa", "Canada", "China"}));

    txtDepart.setModel(
        new DefaultComboBoxModel<>(
            new String[] {"India\t", "Srilanka", "Uk", "Usa", "Canada", "China"}));

    GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel1Layout
                    .createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addGroup(
                                jPanel1Layout
                                    .createSequentialGroup()
                                    .addGroup(
                                        jPanel1Layout
                                            .createParallelGroup(GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3))
                                    .addGroup(
                                        jPanel1Layout
                                            .createParallelGroup(GroupLayout.Alignment.LEADING)
                                            .addGroup(
                                                jPanel1Layout
                                                    .createSequentialGroup()
                                                    .addGap(38, 38, 38)
                                                    .addComponent(txtFlightID))
                                            .addGroup(
                                                jPanel1Layout
                                                    .createSequentialGroup()
                                                    .addGap(28, 28, 28)
                                                    .addComponent(
                                                        txtFlightName,
                                                        GroupLayout.PREFERRED_SIZE,
                                                        136,
                                                        GroupLayout.PREFERRED_SIZE))))
                            .addGroup(
                                GroupLayout.Alignment.TRAILING,
                                jPanel1Layout
                                    .createSequentialGroup()
                                    .addGroup(
                                        jPanel1Layout
                                            .createParallelGroup(GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                    .addPreferredGap(
                                        LayoutStyle.ComponentPlacement.RELATED,
                                        GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                    .addGroup(
                                        jPanel1Layout
                                            .createParallelGroup(
                                                GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtSource, 0, 136, Short.MAX_VALUE)
                                            .addComponent(
                                                txtDepart,
                                                0,
                                                GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE))))
                    .addGap(103, 103, 103)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(
                                jPanel1Layout
                                    .createSequentialGroup()
                                    .addGroup(
                                        jPanel1Layout
                                            .createParallelGroup(GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                    .addGap(62, 62, 62)
                                    .addGroup(
                                        jPanel1Layout
                                            .createParallelGroup(
                                                GroupLayout.Alignment.LEADING, false)
                                            .addComponent(
                                                txtDate,
                                                GroupLayout.DEFAULT_SIZE,
                                                174,
                                                Short.MAX_VALUE)
                                            .addComponent(txtTime)
                                            .addComponent(txtArriveTime)))
                            .addGroup(
                                jPanel1Layout
                                    .createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(52, 52, 52)
                                    .addComponent(
                                        txtFlightCharge,
                                        GroupLayout.PREFERRED_SIZE,
                                        172,
                                        GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(
                GroupLayout.Alignment.TRAILING,
                jPanel1Layout
                    .createSequentialGroup()
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(
                        jButton1, GroupLayout.PREFERRED_SIZE, 117, GroupLayout.PREFERRED_SIZE)
                    .addGap(29, 29, 29)
                    .addComponent(
                        jButton2, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)
                    .addGap(39, 39, 39)));
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel1Layout
                    .createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addGroup(
                                jPanel1Layout
                                    .createParallelGroup(GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txtFlightID)
                                    .addComponent(jLabel6))
                            .addComponent(
                                txtDate,
                                GroupLayout.PREFERRED_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(
                                txtFlightName,
                                GroupLayout.PREFERRED_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(
                                txtTime,
                                GroupLayout.PREFERRED_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE))
                    .addGap(28, 28, 28)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(
                                txtArriveTime,
                                GroupLayout.PREFERRED_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(
                                txtSource,
                                GroupLayout.PREFERRED_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE))
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(
                                jPanel1Layout
                                    .createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addGroup(
                                        jPanel1Layout
                                            .createParallelGroup(GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(
                                                txtDepart,
                                                GroupLayout.PREFERRED_SIZE,
                                                GroupLayout.DEFAULT_SIZE,
                                                GroupLayout.PREFERRED_SIZE)))
                            .addGroup(
                                jPanel1Layout
                                    .createSequentialGroup()
                                    .addGap(34, 34, 34)
                                    .addGroup(
                                        jPanel1Layout
                                            .createParallelGroup(GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel9)
                                            .addComponent(
                                                txtFlightCharge,
                                                GroupLayout.PREFERRED_SIZE,
                                                GroupLayout.DEFAULT_SIZE,
                                                GroupLayout.PREFERRED_SIZE))))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(
                                jButton1,
                                GroupLayout.PREFERRED_SIZE,
                                46,
                                GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                jButton2,
                                GroupLayout.PREFERRED_SIZE,
                                46,
                                GroupLayout.PREFERRED_SIZE))
                    .addGap(43, 43, 43)));

    GroupLayout layout = new GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(
                        jPanel1,
                        GroupLayout.PREFERRED_SIZE,
                        GroupLayout.DEFAULT_SIZE,
                        GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(22, Short.MAX_VALUE)));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(
                GroupLayout.Alignment.TRAILING,
                layout
                    .createSequentialGroup()
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(
                        jPanel1,
                        GroupLayout.PREFERRED_SIZE,
                        GroupLayout.DEFAULT_SIZE,
                        GroupLayout.PREFERRED_SIZE)
                    .addGap(39, 39, 39)));

    pack();
  } // </editor-fold>//GEN-END:initComponents

  public void autoID() {
    try {
      Class.forName("com.mysql.cj.jdbc.Driver");
      connection =
          DriverManager.getConnection("jdbc:mysql://localhost/airline", "root", "password");
      Statement statement = connection.createStatement();
      ResultSet resultSet = statement.executeQuery("select MAX(ID) from flight");
      resultSet.next();
      resultSet.getString("MAX(ID)");
      if (resultSet.getString("MAX(ID)") == null) {
        txtFlightID.setText("FO001");
      } else {
        long ID = Long.parseLong(resultSet.getString("MAX(ID)").substring(2));
        ID++;
        txtFlightID.setText("FO" + String.format("%03d", ID));
      }

    } catch (ClassNotFoundException | SQLException ex) {
      Logger.getLogger(addCustomer.class.getName()).log(Level.SEVERE, null, ex);
    }
  }

  private void jButton1ActionPerformed(ActionEvent evt) { // GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:

    String ID = txtFlightID.getText();
    String flightName = txtFlightName.getText();
    String source = Objects.requireNonNull(txtSource.getSelectedItem()).toString().trim();
    String depart = Objects.requireNonNull(txtDepart.getSelectedItem()).toString().trim();
    DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    String date = dateFormat.format(txtDate.getDate());
    String departTime = txtTime.getText();
    String arriveTime = txtArriveTime.getText();
    String flightCharge = txtFlightCharge.getText();

    try {
      Class.forName("com.mysql.cj.jdbc.Driver");
      connection =
          DriverManager.getConnection("jdbc:mysql://localhost/airline", "root", "password");
      preparedStatement =
          connection.prepareStatement(
              "INSERT INTO FLIGHT(ID, flightName, source, depart, date, departTime, arriveTime, flightCharge) VALUES (?, ?, ?, ?, ?, ?, ?, ?)");

      preparedStatement.setString(1, ID);
      preparedStatement.setString(2, flightName);
      preparedStatement.setString(3, source);
      preparedStatement.setString(4, depart);
      preparedStatement.setString(5, date);
      preparedStatement.setString(6, departTime);
      preparedStatement.setString(7, arriveTime);
      preparedStatement.setString(8, flightCharge);
      preparedStatement.executeUpdate();

      JOptionPane.showMessageDialog(null, "Flight Created.........");
    } catch (ClassNotFoundException | SQLException ex) {
      Logger.getLogger(addFlight.class.getName()).log(Level.SEVERE, null, ex);
    }
  } // GEN-LAST:event_jButton1ActionPerformed

  private void jButton2ActionPerformed(ActionEvent evt) { // GEN-FIRST:event_jButton2ActionPerformed
    // TODO add your handling code here:

    this.hide();
  } // GEN-LAST:event_jButton2ActionPerformed

  private JTextField txtArriveTime;
  private JDateChooser txtDate;
  private JComboBox<String> txtDepart;
  private JTextField txtTime;
  private JTextField txtFlightCharge;
  private JLabel txtFlightID;
  private JTextField txtFlightName;
  private JComboBox<String> txtSource;
  // End of variables declaration//GEN-END:variables
}
