import java.awt.*;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.border.TitledBorder;
import static java.awt.Font.BOLD;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
public class Login extends JFrame {

  /** Creates new form Login */
  public Login() {
    initComponents();
  }

  Connection con;
  PreparedStatement pst;

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  private void initComponents() {

    jPanel1 = new JPanel();
    jLabel1 = new JLabel();
    jLabel2 = new JLabel();
    jButton1 = new JButton();
    jButton2 = new JButton();
    txtuser = new JTextField();
    txtpass = new JPasswordField();

    setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBorder(
        BorderFactory.createTitledBorder(
            null,
            "Login",
            TitledBorder.DEFAULT_JUSTIFICATION,
            TitledBorder.DEFAULT_POSITION,
            new Font("Tahoma", BOLD, 18)));

    jLabel1.setText("Username");

    jLabel2.setText("Password");

    jButton1.setText("Login");
    jButton1.addActionListener(
        evt -> {
          try {
            jButton1ActionPerformed(evt);
          } catch (Exception e) {
            e.printStackTrace();
          }
        });

    jButton2.setText("Cancel");

    GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel1Layout
                    .createSequentialGroup()
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(
                                jPanel1Layout
                                    .createSequentialGroup()
                                    .addGap(50, 50, 50)
                                    .addGroup(
                                        jPanel1Layout
                                            .createParallelGroup(GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                    .addGap(52, 52, 52)
                                    .addGroup(
                                        jPanel1Layout
                                            .createParallelGroup(
                                                GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtuser)
                                            .addComponent(
                                                txtpass,
                                                GroupLayout.DEFAULT_SIZE,
                                                177,
                                                Short.MAX_VALUE)))
                            .addGroup(
                                jPanel1Layout
                                    .createSequentialGroup()
                                    .addGap(136, 136, 136)
                                    .addComponent(
                                        jButton1,
                                        GroupLayout.PREFERRED_SIZE,
                                        97,
                                        GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(
                                        jButton2,
                                        GroupLayout.PREFERRED_SIZE,
                                        116,
                                        GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(25, Short.MAX_VALUE)));
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel1Layout
                    .createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(
                                txtuser,
                                GroupLayout.PREFERRED_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE))
                    .addGap(43, 43, 43)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(
                                txtpass,
                                GroupLayout.PREFERRED_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(
                                jButton1,
                                GroupLayout.PREFERRED_SIZE,
                                39,
                                GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                jButton2,
                                GroupLayout.PREFERRED_SIZE,
                                36,
                                GroupLayout.PREFERRED_SIZE))
                    .addGap(45, 45, 45)));

    GroupLayout layout = new GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(
                        jPanel1,
                        GroupLayout.PREFERRED_SIZE,
                        GroupLayout.DEFAULT_SIZE,
                        GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(44, Short.MAX_VALUE)));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(
                        jPanel1,
                        GroupLayout.PREFERRED_SIZE,
                        GroupLayout.DEFAULT_SIZE,
                        GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(22, Short.MAX_VALUE)));
    pack();
    setLocationRelativeTo(null);
  }

  public boolean testLogin(String username, String password) {
    return username.isEmpty() || password.isEmpty();
  }

  public boolean jButton1ActionPerformed(ActionEvent evt) throws Exception {
    // TODO add your handling code here:

    String username = txtuser.getText();
    String password = txtpass.getText();

    if (testLogin(username, password)) {
      JOptionPane.showMessageDialog(this, "Username or Password Blank");
      throw new Exception("Username or Password Blank");
    } else {
      try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost/airline", "root", "password");
        pst = con.prepareStatement("SELECT * FROM USER WHERE username = ? AND password = ?");
        pst.setString(1, username);
        pst.setString(2, password);

        ResultSet rs;
        rs = pst.executeQuery();

        if (rs.next()) {
          Main m = new Main();
          this.dispose();
          m.setVisible(true);

        } else {
          JOptionPane.showMessageDialog(this, "Username or Password do not match");
          txtuser.setText("");
          txtpass.setText("");
          txtuser.requestFocus();
          return false;
        }

      } catch (ClassNotFoundException | SQLException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
      }
    }
    return true;
  }

  public static void main(String[] args) {
    try {
      for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException
        | UnsupportedLookAndFeelException
        | IllegalAccessException
        | InstantiationException ex) {
      Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    }

    /* Create and display the form */
    EventQueue.invokeLater(() -> new Login().setVisible(true));
  }

  // Variables declaration - do not modify //
  private JButton jButton1;
  private JButton jButton2;
  private JLabel jLabel1;
  private JLabel jLabel2;
  private JPanel jPanel1;
  public JPasswordField txtpass;
  public JTextField txtuser;
  // End of variables declaration //
}
