import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
public class Main extends JFrame {

  /** Creates new form Main */
  public Main() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  private void initComponents() {

    jDesktopPane1 = new JDesktopPane();
    jMenuBar1 = new JMenuBar();
    jMenu1 = new JMenu();
    jMenuItem1 = new JMenuItem();
    jMenuItem2 = new JMenuItem();
    jMenu2 = new JMenu();
    jMenuItem3 = new JMenuItem();
    jMenuItem6 = new JMenuItem();
    jMenu3 = new JMenu();
    jMenuItem4 = new JMenuItem();
    jMenu4 = new JMenu();
    jMenuItem5 = new JMenuItem();

    setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    setPreferredSize(new Dimension(1366, 768));

    GroupLayout jDesktopPane1Layout = new GroupLayout(jDesktopPane1);
    jDesktopPane1.setLayout(jDesktopPane1Layout);
    jDesktopPane1Layout.setHorizontalGroup(
        jDesktopPane1Layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE));
    jDesktopPane1Layout.setVerticalGroup(
        jDesktopPane1Layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE));

    jMenu1.setText("Customer");

    jMenuItem1.setText("Add Customer");
    jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
    jMenu1.add(jMenuItem1);

    jMenuItem2.setText("Search Customer");
    jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
    jMenu1.add(jMenuItem2);

    jMenuBar1.add(jMenu1);

    jMenu2.setText("Tickets");

    jMenuItem3.setText("Book Ticket");
    jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
    jMenu2.add(jMenuItem3);

    jMenuItem6.setText("Ticket Report");
    jMenuItem6.addActionListener(this::jMenuItem6ActionPerformed);
    jMenu2.add(jMenuItem6);

    jMenuBar1.add(jMenu2);

    jMenu3.setText("Flight");

    jMenuItem4.setText("Add Flight");
    jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
    jMenu3.add(jMenuItem4);

    jMenuBar1.add(jMenu3);

    jMenu4.setText("User");

    jMenuItem5.setText("User Creation");
    jMenuItem5.addActionListener(this::jMenuItem5ActionPerformed);
    jMenu4.add(jMenuItem5);

    jMenuBar1.add(jMenu4);

    setJMenuBar(jMenuBar1);

    GroupLayout layout = new GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(jDesktopPane1));
    layout.setVerticalGroup(
        layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(jDesktopPane1));
    pack();
  }

  private void jMenuItem1ActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:

    addCustomer cus = new addCustomer();
    jDesktopPane1.add(cus);
    cus.setVisible(true);
  }

  private void jMenuItem2ActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:

    searchCustomer scus = new searchCustomer();
    jDesktopPane1.add(scus);
    scus.setVisible(true);
  }

  private void jMenuItem4ActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:

    addFlight f = new addFlight();
    jDesktopPane1.add(f);
    f.setVisible(true);
  }

  private void jMenuItem3ActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:

    ticket t = new ticket();
    jDesktopPane1.add(t);
    t.setVisible(true);
  }

  private void jMenuItem6ActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:

    ticketReport ti = new ticketReport();
    jDesktopPane1.add(ti);
    ti.setVisible(true);
  }

  private void jMenuItem5ActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:

    userCreation u = new userCreation();
    jDesktopPane1.add(u);
    u.setVisible(true);
  }

  public static void main(String[] args) {
    try {
      for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException
        | UnsupportedLookAndFeelException
        | IllegalAccessException
        | InstantiationException ex) {
      Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
    }

    /* Create and display the form */
    EventQueue.invokeLater(() -> new Main().setVisible(true));
  }

  // Variables declaration - do not modify //
  private JDesktopPane jDesktopPane1;
  private JMenu jMenu1;
  private JMenu jMenu2;
  private JMenu jMenu3;
  private JMenu jMenu4;
  private JMenuBar jMenuBar1;
  private JMenuItem jMenuItem1;
  private JMenuItem jMenuItem2;
  private JMenuItem jMenuItem3;
  private JMenuItem jMenuItem4;
  private JMenuItem jMenuItem5;
  private JMenuItem jMenuItem6;
  // End of variables declaration //
}
