/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Main extends JFrame {

  /** Creates new form Main */
  public Main() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  // <editor-fold default state="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jDesktopPane1 = new JDesktopPane();
    JMenuBar jMenuBar1 = new JMenuBar();
    JMenu jMenu1 = new JMenu();
    JMenuItem jMenuItem1 = new JMenuItem();
    JMenuItem jMenuItem2 = new JMenuItem();
    JMenu jMenu2 = new JMenu();
    JMenuItem jMenuItem3 = new JMenuItem();
    JMenuItem jMenuItem6 = new JMenuItem();
    JMenu jMenu3 = new JMenu();
    JMenuItem jMenuItem4 = new JMenuItem();
    JMenu jMenu4 = new JMenu();
    JMenuItem jMenuItem5 = new JMenuItem();

    setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    setPreferredSize(new Dimension(1366, 768));

    GroupLayout jDesktopPane1Layout = new GroupLayout(jDesktopPane1);
    jDesktopPane1.setLayout(jDesktopPane1Layout);
    jDesktopPane1Layout.setHorizontalGroup(
        jDesktopPane1Layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE));
    jDesktopPane1Layout.setVerticalGroup(
        jDesktopPane1Layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE));

    jMenu1.setText("Customer");

    jMenuItem1.setText("Add Customer");
    jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
    jMenu1.add(jMenuItem1);

    jMenuItem2.setText("Search Customer");
    jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
    jMenu1.add(jMenuItem2);

    jMenuBar1.add(jMenu1);

    jMenu2.setText("Tickets");

    jMenuItem3.setText("Book Ticket");
    jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
    jMenu2.add(jMenuItem3);

    jMenuItem6.setText("Ticket Report");
    jMenuItem6.addActionListener(this::jMenuItem6ActionPerformed);
    jMenu2.add(jMenuItem6);

    jMenuBar1.add(jMenu2);

    jMenu3.setText("Flight");

    jMenuItem4.setText("Add Flight");
    jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
    jMenu3.add(jMenuItem4);

    jMenuBar1.add(jMenu3);

    jMenu4.setText("User");

    jMenuItem5.setText("User Creation");
    jMenuItem5.addActionListener(this::jMenuItem5ActionPerformed);
    jMenu4.add(jMenuItem5);

    jMenuBar1.add(jMenu4);

    setJMenuBar(jMenuBar1);

    GroupLayout layout = new GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(jDesktopPane1));
    layout.setVerticalGroup(
        layout.createParallelGroup(GroupLayout.Alignment.LEADING).addComponent(jDesktopPane1));

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void jMenuItem1ActionPerformed(
      ActionEvent evt) { // GEN-FIRST:event_jMenuItem1ActionPerformed
    // TODO add your handling code here:

    addCustomer customer = new addCustomer();
    jDesktopPane1.add(customer);
    customer.setVisible(true);
  } // GEN-LAST:event_jMenuItem1ActionPerformed

  private void jMenuItem2ActionPerformed(
      ActionEvent evt) { // GEN-FIRST:event_jMenuItem2ActionPerformed
    // TODO add your handling code here:

    searchCustomer searchCustomer = new searchCustomer();
    jDesktopPane1.add(searchCustomer);
    searchCustomer.setVisible(true);
  } // GEN-LAST:event_jMenuItem2ActionPerformed

  private void jMenuItem4ActionPerformed(
      ActionEvent evt) { // GEN-FIRST:event_jMenuItem4ActionPerformed
    // TODO add your handling code here:
    addFlight flight = new addFlight();
    jDesktopPane1.add(flight);
    flight.setVisible(true);
  } // GEN-LAST:event_jMenuItem4ActionPerformed

  private void jMenuItem3ActionPerformed(
      ActionEvent evt) { // GEN-FIRST:event_jMenuItem3ActionPerformed
    // TODO add your handling code here:
    ticket ticket = new ticket();
    jDesktopPane1.add(ticket);
    ticket.setVisible(true);
  } // GEN-LAST:event_jMenuItem3ActionPerformed

  private void jMenuItem6ActionPerformed(
      ActionEvent evt) { // GEN-FIRST:event_jMenuItem6ActionPerformed
    // TODO add your handling code here:

    ticketReport ticketReport = new ticketReport();
    jDesktopPane1.add(ticketReport);
    ticketReport.setVisible(true);
  } // GEN-LAST:event_jMenuItem6ActionPerformed

  private void jMenuItem5ActionPerformed(
      ActionEvent evt) { // GEN-FIRST:event_jMenuItem5ActionPerformed
    // TODO add your handling code here:

    userCreation user = new userCreation();
    jDesktopPane1.add(user);
    user.setVisible(true);
  } // GEN-LAST:event_jMenuItem5ActionPerformed

  /** @param args the command line arguments */
  public static void main(String[] args) {
    /* Set the Nimbus look and feel */
    // <editor-fold default state="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException
        | InstantiationException
        | IllegalAccessException
        | UnsupportedLookAndFeelException ex) {
      Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
    }
    // </editor-fold>

    /* Create and display the form */
    EventQueue.invokeLater(() -> new Main().setVisible(true));
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private JDesktopPane jDesktopPane1;
  // End of variables declaration//GEN-END:variables
}
