import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class ticketReport extends JInternalFrame {

  /** Creates new form ticketReport */
  public ticketReport() {
    initComponents();
    LoadData();
  }

  Connection connection;
  PreparedStatement preparedStatement;
  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  // <editor-fold default state="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    JScrollPane jScrollPane1 = new JScrollPane();
    jTable1 = new JTable();
    JButton jButton1 = new JButton();

    jTable1.setModel(
        new DefaultTableModel(
            new Object[][] {},
            new String[] {
              "Ticket No", "Flight No", "Customer ID", "Class", "Price", "Seats", "Date"
            }));
    jScrollPane1.setViewportView(jTable1);

    jButton1.setText("Cancel");
    jButton1.addActionListener(this::jButton1ActionPerformed);

    GroupLayout layout = new GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGroup(
                        layout
                            .createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(
                                        jScrollPane1,
                                        GroupLayout.PREFERRED_SIZE,
                                        509,
                                        GroupLayout.PREFERRED_SIZE))
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addGap(226, 226, 226)
                                    .addComponent(
                                        jButton1,
                                        GroupLayout.PREFERRED_SIZE,
                                        155,
                                        GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(35, Short.MAX_VALUE)));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addComponent(
                        jScrollPane1, GroupLayout.PREFERRED_SIZE, 259, GroupLayout.PREFERRED_SIZE)
                    .addGap(35, 35, 35)
                    .addComponent(
                        jButton1, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(37, Short.MAX_VALUE)));
    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(ActionEvent evt) { // GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:
    this.hide();
  } // GEN-LAST:event_jButton1ActionPerformed

  public void LoadData() {
    try {
      Class.forName("com.mysql.cj.jdbc.Driver");
      connection =
          DriverManager.getConnection("jdbc:mysql://localhost/airline", "root", "password");
      preparedStatement = connection.prepareStatement("SELECT * from ticket");
      ResultSet resultSet = preparedStatement.executeQuery();

      ResultSetMetaData resultSetMetaData = resultSet.getMetaData();
      int number;
      number = resultSetMetaData.getColumnCount();

      DefaultTableModel defaultTableModel = (DefaultTableModel) jTable1.getModel();
      defaultTableModel.setRowCount(0);

      while (resultSet.next()) {
        Vector<String> vector = new Vector<>();

        for (int i = 1; i <= number; i++) {
          vector.add(resultSet.getString("ID"));
          vector.add(resultSet.getString("flightID"));
          vector.add(resultSet.getString("customerID"));
          vector.add(resultSet.getString("class"));
          vector.add(resultSet.getString("price"));
          vector.add(resultSet.getString("seats"));
          vector.add(resultSet.getString("date"));
        }

        defaultTableModel.addRow(vector);
      }

    } catch (ClassNotFoundException | SQLException ex) {
      Logger.getLogger(ticket.class.getName()).log(Level.SEVERE, null, ex);
    }
  }

  private JTable jTable1;
  // End of variables declaration//GEN-END:variables
}
