import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.event.ChangeEvent;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.*;
import java.util.Objects;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import static java.awt.Font.BOLD;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class ticket extends JInternalFrame {

  /** Creates new form ticket */
  public ticket() {
    initComponents();
    autoID();
  }

  Connection con;
  PreparedStatement pst;

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  private void initComponents() {

    jPanel1 = new JPanel();
    txtsource = new JComboBox<>();
    txtdepart = new JComboBox<>();
    jLabel1 = new JLabel();
    jLabel2 = new JLabel();
    jButton3 = new JButton();
    jScrollPane1 = new JScrollPane();
    jTable1 = new JTable();
    jLabel3 = new JLabel();
    txtticketno = new JLabel();
    jPanel3 = new JPanel();
    jLabel5 = new JLabel();
    jLabel6 = new JLabel();
    jLabel7 = new JLabel();
    txtcustid = new JTextField();
    jLabel8 = new JLabel();
    txtfirstname = new JLabel();
    txtlastname = new JLabel();
    txtpassport = new JLabel();
    jButton4 = new JButton();
    jPanel2 = new JPanel();
    jLabel12 = new JLabel();
    jLabel13 = new JLabel();
    jLabel14 = new JLabel();
    jLabel15 = new JLabel();
    jLabel16 = new JLabel();
    jLabel17 = new JLabel();
    flightno = new JLabel();
    flightname = new JLabel();
    txtdept = new JLabel();
    txtclass = new JComboBox<>();
    txtprice = new JTextField();
    txtseats = new JSpinner();
    jButton1 = new JButton();
    jButton2 = new JButton();
    txttotal = new JLabel();

    jPanel1.setBorder(
        BorderFactory.createTitledBorder(
            null,
            "Select Country",
            TitledBorder.DEFAULT_JUSTIFICATION,
            TitledBorder.DEFAULT_POSITION,
            new Font("Tahoma", BOLD, 12)));

    txtsource.setModel(
        new DefaultComboBoxModel<>(
            new String[] {"India", "Srilanka", "UK", "USA", "Canada", "China"}));

    txtdepart.setModel(
        new DefaultComboBoxModel<>(
            new String[] {"India\t", "Srilanka", "UK", "USA", "Canada", "China"}));

    jLabel1.setText("Source");

    jLabel2.setText("Departure");

    jButton3.setText("Search");
    jButton3.addActionListener(this::jButton3ActionPerformed);

    GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel1Layout
                    .createSequentialGroup()
                    .addContainerGap()
                    .addComponent(
                        txtsource, GroupLayout.PREFERRED_SIZE, 124, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                    .addComponent(
                        txtdepart, GroupLayout.PREFERRED_SIZE, 111, GroupLayout.PREFERRED_SIZE)
                    .addGap(35, 35, 35))
            .addGroup(
                jPanel1Layout
                    .createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addComponent(jLabel1)
                    .addPreferredGap(
                        LayoutStyle.ComponentPlacement.RELATED,
                        GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(87, 87, 87))
            .addGroup(
                GroupLayout.Alignment.TRAILING,
                jPanel1Layout
                    .createSequentialGroup()
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3)
                    .addGap(49, 49, 49)));
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel1Layout
                    .createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                    .addGap(18, 18, 18)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(
                                txtsource,
                                GroupLayout.PREFERRED_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                txtdepart,
                                GroupLayout.PREFERRED_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                    .addComponent(jButton3)
                    .addContainerGap()));

    jTable1.setModel(
        new DefaultTableModel(
            new Object[][] {},
            new String[] {
              "Flight Number",
              "Flight Name",
              "Source",
              "Departure",
              "Date",
              "Depart Time",
              "Arrive Time",
              "Charge"
            }));
    jTable1.addMouseListener(
        new MouseAdapter() {
          public void mouseClicked(MouseEvent evt) {
            jTable1MouseClicked();
          }
        });
    jScrollPane1.setViewportView(jTable1);

    jLabel3.setText("Ticket No");

    txtticketno.setFont(new Font("Tahoma", BOLD, 24)); // NOI18N
    txtticketno.setForeground(new Color(255, 0, 0));
    txtticketno.setText("Ticket No");

    jLabel5.setText("Customer ID");

    jLabel6.setText("First Name");

    jLabel7.setText("Last Name");

    jLabel8.setText("Passport No");

    txtfirstname.setFont(new Font("Tahoma", BOLD, 14));
    txtfirstname.setForeground(new Color(255, 0, 0));
    txtfirstname.setText("jLabel9");

    txtlastname.setFont(new Font("Tahoma", BOLD, 14));
    txtlastname.setForeground(new Color(255, 0, 0));
    txtlastname.setText("jLabel10");

    txtpassport.setFont(new Font("Tahoma", BOLD, 14));
    txtpassport.setForeground(new Color(255, 0, 0));
    txtpassport.setText("jLabel11");

    jButton4.setText("Search");
    jButton4.addActionListener(this::jButton4ActionPerformed);

    GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel3Layout
                    .createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addGroup(
                        jPanel3Layout
                            .createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(
                                jPanel3Layout
                                    .createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(34, 34, 34)
                                    .addComponent(
                                        txtcustid,
                                        GroupLayout.PREFERRED_SIZE,
                                        151,
                                        GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(
                                        LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                    .addComponent(jButton4))
                            .addGroup(
                                jPanel3Layout
                                    .createSequentialGroup()
                                    .addGroup(
                                        jPanel3Layout
                                            .createParallelGroup(GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                    .addGap(56, 56, 56)
                                    .addGroup(
                                        jPanel3Layout
                                            .createParallelGroup(GroupLayout.Alignment.LEADING)
                                            .addComponent(txtpassport)
                                            .addComponent(txtlastname)
                                            .addComponent(txtfirstname))))
                    .addContainerGap()));
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel3Layout
                    .createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addGroup(
                        jPanel3Layout
                            .createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(
                                txtcustid,
                                GroupLayout.PREFERRED_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))
                    .addGap(26, 26, 26)
                    .addGroup(
                        jPanel3Layout
                            .createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtfirstname))
                    .addGap(31, 31, 31)
                    .addGroup(
                        jPanel3Layout
                            .createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtlastname))
                    .addGap(36, 36, 36)
                    .addGroup(
                        jPanel3Layout
                            .createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtpassport))
                    .addContainerGap(37, Short.MAX_VALUE)));

    jLabel12.setText("Flight No");

    jLabel13.setText("Flight Name");

    jLabel14.setText("Depart Time");

    jLabel15.setText("Class");

    jLabel16.setText("Price");

    jLabel17.setText("Seats");

    flightno.setFont(new Font("Tahoma", BOLD, 12)); // NOI18N
    flightno.setForeground(new Color(255, 0, 0));
    flightno.setText("jLabel18");

    flightname.setFont(new Font("Tahoma", BOLD, 12)); // NOI18N
    flightname.setForeground(new Color(255, 0, 0));
    flightname.setText("jLabel19");

    txtdept.setFont(new Font("Tahoma", BOLD, 12)); // NOI18N
    txtdept.setForeground(new Color(255, 0, 0));
    txtdept.setText("jLabel20");

    txtclass.setModel(new DefaultComboBoxModel<>(new String[] {"Economy", "Business"}));

    txtseats.addChangeListener(this::txtseatsStateChanged);

    GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel2Layout
                    .createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addGroup(
                        jPanel2Layout
                            .createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addGroup(
                                jPanel2Layout
                                    .createParallelGroup(GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15, GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, GroupLayout.Alignment.LEADING)
                                    .addGroup(
                                        jPanel2Layout
                                            .createParallelGroup(GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13)))
                            .addGroup(
                                jPanel2Layout
                                    .createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addGap(35, 35, 35)))
                    .addGroup(
                        jPanel2Layout
                            .createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(
                                jPanel2Layout
                                    .createSequentialGroup()
                                    .addGap(60, 60, 60)
                                    .addGroup(
                                        jPanel2Layout
                                            .createParallelGroup(GroupLayout.Alignment.LEADING)
                                            .addComponent(flightname)
                                            .addComponent(txtdept)
                                            .addComponent(flightno)))
                            .addGroup(
                                jPanel2Layout
                                    .createSequentialGroup()
                                    .addGap(50, 50, 50)
                                    .addGroup(
                                        jPanel2Layout
                                            .createParallelGroup(
                                                GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtclass, 0, 116, Short.MAX_VALUE)
                                            .addComponent(txtprice)
                                            .addComponent(
                                                txtseats,
                                                GroupLayout.PREFERRED_SIZE,
                                                64,
                                                GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(151, Short.MAX_VALUE)));
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel2Layout
                    .createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addGroup(
                        jPanel2Layout
                            .createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(flightno))
                    .addGap(28, 28, 28)
                    .addGroup(
                        jPanel2Layout
                            .createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(flightname))
                    .addGap(31, 31, 31)
                    .addGroup(
                        jPanel2Layout
                            .createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtdept))
                    .addGap(23, 23, 23)
                    .addGroup(
                        jPanel2Layout
                            .createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(
                                txtclass,
                                GroupLayout.PREFERRED_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(
                        jPanel2Layout
                            .createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(
                                txtprice,
                                GroupLayout.PREFERRED_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(
                        jPanel2Layout
                            .createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(
                                txtseats,
                                GroupLayout.PREFERRED_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    jButton1.setText("Book");
    jButton1.addActionListener(this::jButton1ActionPerformed);

    jButton2.setText("Cancel");
    jButton2.addActionListener(this::jButton2ActionPerformed);

    txttotal.setFont(new Font("Tahoma", BOLD, 24)); // NOI18N
    txttotal.setForeground(new Color(255, 0, 0));
    txttotal.setText("jLabel4");

    GroupLayout layout = new GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addGroup(
                        layout
                            .createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addComponent(
                                        jPanel1,
                                        GroupLayout.PREFERRED_SIZE,
                                        GroupLayout.DEFAULT_SIZE,
                                        GroupLayout.PREFERRED_SIZE)
                                    .addGroup(
                                        layout
                                            .createParallelGroup(GroupLayout.Alignment.LEADING)
                                            .addGroup(
                                                layout
                                                    .createSequentialGroup()
                                                    .addGap(44, 44, 44)
                                                    .addComponent(jLabel3))
                                            .addGroup(
                                                layout
                                                    .createSequentialGroup()
                                                    .addPreferredGap(
                                                        LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(txtticketno)))
                                    .addGap(41, 41, 41)
                                    .addComponent(
                                        jPanel3,
                                        GroupLayout.DEFAULT_SIZE,
                                        GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                    .addGap(31, 31, 31))
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addGroup(
                                        layout
                                            .createParallelGroup(GroupLayout.Alignment.LEADING)
                                            .addComponent(
                                                jScrollPane1,
                                                GroupLayout.PREFERRED_SIZE,
                                                534,
                                                GroupLayout.PREFERRED_SIZE)
                                            .addGroup(
                                                layout
                                                    .createSequentialGroup()
                                                    .addGap(207, 207, 207)
                                                    .addComponent(
                                                        txttotal,
                                                        GroupLayout.PREFERRED_SIZE,
                                                        106,
                                                        GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(
                                        layout
                                            .createParallelGroup(GroupLayout.Alignment.LEADING)
                                            .addGroup(
                                                layout
                                                    .createSequentialGroup()
                                                    .addGap(51, 51, 51)
                                                    .addComponent(
                                                        jButton1,
                                                        GroupLayout.PREFERRED_SIZE,
                                                        138,
                                                        GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(
                                                        LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(
                                                        jButton2,
                                                        GroupLayout.PREFERRED_SIZE,
                                                        134,
                                                        GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(
                                                layout
                                                    .createSequentialGroup()
                                                    .addGap(33, 33, 33)
                                                    .addComponent(
                                                        jPanel2,
                                                        GroupLayout.DEFAULT_SIZE,
                                                        GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE)
                                                    .addContainerGap()))))));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGroup(
                        layout
                            .createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addGap(42, 42, 42)
                                    .addComponent(
                                        jPanel1,
                                        GroupLayout.PREFERRED_SIZE,
                                        GroupLayout.DEFAULT_SIZE,
                                        GroupLayout.PREFERRED_SIZE))
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addGap(53, 53, 53)
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtticketno))
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addComponent(
                                        jPanel3,
                                        GroupLayout.PREFERRED_SIZE,
                                        GroupLayout.DEFAULT_SIZE,
                                        GroupLayout.PREFERRED_SIZE)))
                    .addGroup(
                        layout
                            .createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(
                                        jScrollPane1,
                                        GroupLayout.PREFERRED_SIZE,
                                        213,
                                        GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addComponent(
                                        txttotal,
                                        GroupLayout.PREFERRED_SIZE,
                                        24,
                                        GroupLayout.PREFERRED_SIZE))
                            .addGroup(
                                layout
                                    .createSequentialGroup()
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(
                                        jPanel2,
                                        GroupLayout.PREFERRED_SIZE,
                                        GroupLayout.DEFAULT_SIZE,
                                        GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(
                                        layout
                                            .createParallelGroup(GroupLayout.Alignment.BASELINE)
                                            .addComponent(
                                                jButton1,
                                                GroupLayout.PREFERRED_SIZE,
                                                41,
                                                GroupLayout.PREFERRED_SIZE)
                                            .addComponent(
                                                jButton2,
                                                GroupLayout.PREFERRED_SIZE,
                                                41,
                                                GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    pack();
  }

  private void jButton3ActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:

    String source = Objects.requireNonNull(txtsource.getSelectedItem()).toString().trim();
    String depart = Objects.requireNonNull(txtdepart.getSelectedItem()).toString().trim();

    try {
      Class.forName("com.mysql.cj.jdbc.Driver");
      con = DriverManager.getConnection("jdbc:mysql://localhost/airline", "root", "password");
      pst = con.prepareStatement("SELECT * FROM FLIGHT WHERE source = ? AND depart = ?");

      pst.setString(1, source);
      pst.setString(2, depart);
      ResultSet rs = pst.executeQuery();

      ResultSetMetaData rsm = rs.getMetaData();
      int c;
      c = rsm.getColumnCount();

      DefaultTableModel Df = (DefaultTableModel) jTable1.getModel();
      Df.setRowCount(0);

      while (rs.next()) {
        Vector<String> v2 = new Vector<>();

        for (int i = 1; i <= c; i++) {
          v2.add(rs.getString("ID"));
          v2.add(rs.getString("flightName"));
          v2.add(rs.getString("source"));
          v2.add(rs.getString("depart"));
          v2.add(rs.getString("date"));
          v2.add(rs.getString("departTime"));
          v2.add(rs.getString("arriveTime"));
          v2.add(rs.getString("flightCharge"));
        }

        Df.addRow(v2);
      }

    } catch (ClassNotFoundException | SQLException ex) {
      Logger.getLogger(ticket.class.getName()).log(Level.SEVERE, null, ex);
    }
  }

  public void autoID() {
    try {
      Class.forName("com.mysql.cj.jdbc.Driver");
      con = DriverManager.getConnection("jdbc:mysql://localhost/airline", "root", "password");
      Statement s = con.createStatement();
      ResultSet rs = s.executeQuery("SELECT MAX(ID) FROM TICKET");
      rs.next();
      rs.getString("MAX(ID)");
      if (rs.getString("MAX(ID)") == null) {
        txtticketno.setText("TO001");
      } else {
        long id = Long.parseLong(rs.getString("MAX(ID)").substring(2));
        id++;
        txtticketno.setText("TO" + String.format("%03d", id));
      }

    } catch (ClassNotFoundException | SQLException ex) {
      Logger.getLogger(addCustomer.class.getName()).log(Level.SEVERE, null, ex);
    }
  }

  private void jButton4ActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:

    String id = txtcustid.getText();

    try {
      Class.forName("com.mysql.cj.jdbc.Driver");
      con = DriverManager.getConnection("jdbc:mysql://localhost/airline", "root", "password");
      pst = con.prepareStatement("SELECT * FROM CUSTOMER WHERE ID = ?");
      pst.setString(1, id);
      ResultSet rs = pst.executeQuery();

      if (!rs.next()) {
        JOptionPane.showMessageDialog(this, "Record not found");
      } else {
        String fname = rs.getString("firstName");
        String lname = rs.getString("lastName");

        String passport = rs.getString("passport");

        txtfirstname.setText(fname.trim());
        txtlastname.setText(lname.trim());

        txtpassport.setText(passport.trim());
      }

    } catch (ClassNotFoundException | SQLException ex) {
      Logger.getLogger(ticket.class.getName()).log(Level.SEVERE, null, ex);
    }
  }

  private void jTable1MouseClicked() {
    // TODO add your handling code here:

    DefaultTableModel Df = (DefaultTableModel) jTable1.getModel();

    int selectIndex = jTable1.getSelectedRow();

    flightno.setText(Df.getValueAt(selectIndex, 0).toString());
    flightname.setText(Df.getValueAt(selectIndex, 1).toString());
    txtdept.setText(Df.getValueAt(selectIndex, 5).toString());
    txtprice.setText(Df.getValueAt(selectIndex, 7).toString());
  }

  public int calculateTotal(int price, int quantity) {
    if (price > 0 && quantity > 0) {
      if (price > 50000 || quantity > 50) {
        return 0;
      } else {
        return price * quantity;
      }
    } else {
      return 0;
    }
  }

  public void txtseatsStateChanged(ChangeEvent evt) {
    // TODO add your handling code here:

    int price = Integer.parseInt(txtprice.getText());
    int qty = Integer.parseInt(txtseats.getValue().toString());

    int tot = calculateTotal(price, qty);

    if (tot == 0) {
      System.out.println("Invalid price or quantity");
    } else {
      txttotal.setText(String.valueOf(tot));
    }
  }

  private void jButton1ActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:

    String ticketid = txtticketno.getText();
    String flightid = flightno.getText();
    String custid = txtcustid.getText();
    String flightclass = Objects.requireNonNull(txtclass.getSelectedItem()).toString().trim();
    String price = txtprice.getText();
    String seats = txtseats.getValue().toString();
    // DateFormat da = new SimpleDateFormat("yyyy-MM-dd");
    int row = jTable1.getSelectedRow();
    int column = 4;
    String date = (String) jTable1.getModel().getValueAt(row, column);

    try {
      Class.forName("com.mysql.cj.jdbc.Driver");
      con = DriverManager.getConnection("jdbc:mysql://localhost/airline", "root", "password");
      pst =
          con.prepareStatement(
              "INSERT INTO TICKET(ID, flightID, customerID, class, price, seats, date) VALUES (?, ?, ?, ?, ?, ?, ?)");

      pst.setString(1, ticketid);
      pst.setString(2, flightid);
      pst.setString(3, custid);
      pst.setString(4, flightclass);
      pst.setString(5, price);
      pst.setString(6, seats);
      pst.setString(7, date);

      pst.executeUpdate();

      JOptionPane.showMessageDialog(null, "Ticket Booked.........");
    } catch (ClassNotFoundException | SQLException ex) {
      Logger.getLogger(addFlight.class.getName()).log(Level.SEVERE, null, ex);
    }
  }

  private void jButton2ActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:

    this.hide();
  }

  // Variables declaration - do not modify //
  private JLabel flightname;
  private JLabel flightno;
  private JButton jButton1;
  private JButton jButton2;
  private JButton jButton3;
  private JButton jButton4;
  private JLabel jLabel1;
  private JLabel jLabel12;
  private JLabel jLabel13;
  private JLabel jLabel14;
  private JLabel jLabel15;
  private JLabel jLabel16;
  private JLabel jLabel17;
  private JLabel jLabel2;
  private JLabel jLabel3;
  private JLabel jLabel5;
  private JLabel jLabel6;
  private JLabel jLabel7;
  private JLabel jLabel8;
  private JPanel jPanel1;
  private JPanel jPanel2;
  private JPanel jPanel3;
  private JScrollPane jScrollPane1;
  private JTable jTable1;
  private JComboBox<String> txtclass;
  private JTextField txtcustid;
  private JComboBox<String> txtdepart;
  private JLabel txtdept;
  private JLabel txtfirstname;
  private JLabel txtlastname;
  private JLabel txtpassport;
  public JTextField txtprice;
  public JSpinner txtseats;
  private JComboBox<String> txtsource;
  private JLabel txtticketno;
  public JLabel txttotal;
  // End of variables declaration //
}
