import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import static java.awt.Font.BOLD;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
public class userCreation extends JInternalFrame {

  /** Creates new form userCreation */
  public userCreation() {
    initComponents();
    autoID();
  }

  Connection con;
  PreparedStatement pst;

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  private void initComponents() {

    jPanel1 = new JPanel();
    jLabel1 = new JLabel();
    jLabel2 = new JLabel();
    jLabel3 = new JLabel();
    jLabel4 = new JLabel();
    jLabel5 = new JLabel();
    txtuserid = new JLabel();
    txtfirstname = new JTextField();
    txtlastname = new JTextField();
    txtusername = new JTextField();
    jButton1 = new JButton();
    jButton2 = new JButton();
    txtpassword = new JPasswordField();

    jPanel1.setBorder(BorderFactory.createTitledBorder("User Creation"));

    jLabel1.setFont(new Font("Tahoma", BOLD, 12)); // NOI18N
    jLabel1.setText("User ID");

    jLabel2.setFont(new Font("Tahoma", BOLD, 12)); // NOI18N
    jLabel2.setText("First Name");

    jLabel3.setFont(new Font("Tahoma", BOLD, 12)); // NOI18N
    jLabel3.setText("Last Name");

    jLabel4.setFont(new Font("Tahoma", BOLD, 12)); // NOI18N
    jLabel4.setText("Username");

    jLabel5.setFont(new Font("Tahoma", BOLD, 12)); // NOI18N
    jLabel5.setText("Password");

    txtuserid.setFont(new Font("Tahoma", BOLD, 18)); // NOI18N
    txtuserid.setForeground(new Color(255, 0, 0));
    txtuserid.setText("jLabel6");

    jButton1.setText("Add");
    jButton1.addActionListener(this::jButton1ActionPerformed);

    jButton2.setText("Cancel");
    jButton2.addActionListener(this::jButton2ActionPerformed);

    GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel1Layout
                    .createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                    .addGap(55, 55, 55)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtuserid)
                            .addComponent(txtfirstname)
                            .addComponent(txtlastname)
                            .addComponent(txtusername)
                            .addComponent(
                                txtpassword, GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(
                GroupLayout.Alignment.TRAILING,
                jPanel1Layout
                    .createSequentialGroup()
                    .addContainerGap(208, Short.MAX_VALUE)
                    .addComponent(
                        jButton1, GroupLayout.PREFERRED_SIZE, 109, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(
                        jButton2, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)));
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel1Layout
                    .createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addGroup(
                                jPanel1Layout
                                    .createSequentialGroup()
                                    .addGroup(
                                        jPanel1Layout
                                            .createParallelGroup(GroupLayout.Alignment.TRAILING)
                                            .addGroup(
                                                jPanel1Layout
                                                    .createSequentialGroup()
                                                    .addGroup(
                                                        jPanel1Layout
                                                            .createParallelGroup(
                                                                GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jLabel1)
                                                            .addComponent(txtuserid))
                                                    .addGap(37, 37, 37)
                                                    .addGroup(
                                                        jPanel1Layout
                                                            .createParallelGroup(
                                                                GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jLabel2)
                                                            .addComponent(
                                                                txtfirstname,
                                                                GroupLayout.PREFERRED_SIZE,
                                                                GroupLayout.DEFAULT_SIZE,
                                                                GroupLayout.PREFERRED_SIZE))
                                                    .addGap(44, 44, 44)
                                                    .addComponent(jLabel3))
                                            .addComponent(
                                                txtlastname,
                                                GroupLayout.PREFERRED_SIZE,
                                                GroupLayout.DEFAULT_SIZE,
                                                GroupLayout.PREFERRED_SIZE))
                                    .addGap(49, 49, 49)
                                    .addComponent(jLabel4))
                            .addComponent(
                                txtusername,
                                GroupLayout.PREFERRED_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE))
                    .addGap(46, 46, 46)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(
                                txtpassword,
                                GroupLayout.PREFERRED_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(
                                jButton1,
                                GroupLayout.PREFERRED_SIZE,
                                48,
                                GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                jButton2,
                                GroupLayout.PREFERRED_SIZE,
                                44,
                                GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()));

    GroupLayout layout = new GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(
                        jPanel1,
                        GroupLayout.PREFERRED_SIZE,
                        GroupLayout.DEFAULT_SIZE,
                        GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(22, Short.MAX_VALUE)));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(
                        jPanel1,
                        GroupLayout.PREFERRED_SIZE,
                        GroupLayout.DEFAULT_SIZE,
                        GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(14, Short.MAX_VALUE)));
    pack();
  }

  private void jButton1ActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:

    String id = txtuserid.getText();
    String firstname = txtfirstname.getText();
    String lastname = txtlastname.getText();
    String username = txtusername.getText();
    String password = txtpassword.getText();

    try {
      Class.forName("com.mysql.cj.jdbc.Driver");
      con = DriverManager.getConnection("jdbc:mysql://localhost/airline", "root", "password");
      pst =
          con.prepareStatement(
              "INSERT INTO USER(ID, firstName, lastName, username, password) VALUES (?, ?, ?, ?, ?)");

      pst.setString(1, id);
      pst.setString(2, firstname);
      pst.setString(3, lastname);
      pst.setString(4, username);
      pst.setString(5, password);

      pst.executeUpdate();

      JOptionPane.showMessageDialog(null, "User Created.........");
    } catch (ClassNotFoundException | SQLException ex) {
      Logger.getLogger(addFlight.class.getName()).log(Level.SEVERE, null, ex);
    }
  }

  private void jButton2ActionPerformed(ActionEvent evt) {
    // TODO add your handling code here:

    this.hide();
  }

  public void autoID() {
    try {
      Class.forName("com.mysql.cj.jdbc.Driver");
      con = DriverManager.getConnection("jdbc:mysql://localhost/airline", "root", "password");
      Statement s = con.createStatement();
      ResultSet rs = s.executeQuery("SELECT MAX(ID) FROM USER");
      rs.next();
      rs.getString("MAX(ID)");
      if (rs.getString("MAX(ID)") == null) {
        txtuserid.setText("UO001");
      } else {
        long id = Long.parseLong(rs.getString("MAX(ID)").substring(2));
        id++;
        txtuserid.setText("UO" + String.format("%03d", id));
      }

    } catch (ClassNotFoundException | SQLException ex) {
      Logger.getLogger(addCustomer.class.getName()).log(Level.SEVERE, null, ex);
    }
  }

  // Variables declaration - do not modify //
  private JButton jButton1;
  private JButton jButton2;
  private JLabel jLabel1;
  private JLabel jLabel2;
  private JLabel jLabel3;
  private JLabel jLabel4;
  private JLabel jLabel5;
  private JPanel jPanel1;
  private JTextField txtfirstname;
  private JTextField txtlastname;
  private JPasswordField txtpassword;
  private JLabel txtuserid;
  private JTextField txtusername;
  // End of variables declaration //
}
