import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import static java.awt.Font.BOLD;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class userCreation extends JInternalFrame {

  /** Creates new form userCreation */
  public userCreation() {
    initComponents();
    autoID();
  }

  Connection connection;
  PreparedStatement preparedStatement;

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  // <editor-fold default state="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    JPanel jPanel1 = new JPanel();
    JLabel jLabel1 = new JLabel();
    JLabel jLabel2 = new JLabel();
    JLabel jLabel3 = new JLabel();
    JLabel jLabel4 = new JLabel();
    JLabel jLabel5 = new JLabel();
    txtUserID = new JLabel();
    txtFirstName = new JTextField();
    txtLastName = new JTextField();
    txtUsername = new JTextField();
    JButton jButton1 = new JButton();
    JButton jButton2 = new JButton();
    txtPassword = new JPasswordField();

    jPanel1.setBorder(BorderFactory.createTitledBorder("User Creation"));

    jLabel1.setFont(new Font("Tahoma", BOLD, 12)); // NOI18N
    jLabel1.setText("User ID");

    jLabel2.setFont(new Font("Tahoma", BOLD, 12)); // NOI18N
    jLabel2.setText("First Name");

    jLabel3.setFont(new Font("Tahoma", BOLD, 12)); // NOI18N
    jLabel3.setText("Last Name");

    jLabel4.setFont(new Font("Tahoma", BOLD, 12)); // NOI18N
    jLabel4.setText("Username");

    jLabel5.setFont(new Font("Tahoma", BOLD, 12)); // NOI18N
    jLabel5.setText("Password");

    txtUserID.setFont(new Font("Tahoma", BOLD, 18)); // NOI18N
    txtUserID.setForeground(new Color(255, 0, 0));
    txtUserID.setText("jLabel6");

    jButton1.setText("Add");
    jButton1.addActionListener(evt -> jButton1ActionPerformed());

    jButton2.setText("Cancel");
    jButton2.addActionListener(evt -> jButton2ActionPerformed());

    GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel1Layout
                    .createSequentialGroup()
                    .addGap(44, 44, 44)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                    .addGap(55, 55, 55)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUserID)
                            .addComponent(txtFirstName)
                            .addComponent(txtLastName)
                            .addComponent(txtUsername)
                            .addComponent(
                                txtPassword, GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                    .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(
                GroupLayout.Alignment.TRAILING,
                jPanel1Layout
                    .createSequentialGroup()
                    .addContainerGap(208, Short.MAX_VALUE)
                    .addComponent(
                        jButton1, GroupLayout.PREFERRED_SIZE, 109, GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(
                        jButton2, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)));
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel1Layout
                    .createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addGroup(
                                jPanel1Layout
                                    .createSequentialGroup()
                                    .addGroup(
                                        jPanel1Layout
                                            .createParallelGroup(GroupLayout.Alignment.TRAILING)
                                            .addGroup(
                                                jPanel1Layout
                                                    .createSequentialGroup()
                                                    .addGroup(
                                                        jPanel1Layout
                                                            .createParallelGroup(
                                                                GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jLabel1)
                                                            .addComponent(txtUserID))
                                                    .addGap(37, 37, 37)
                                                    .addGroup(
                                                        jPanel1Layout
                                                            .createParallelGroup(
                                                                GroupLayout.Alignment.BASELINE)
                                                            .addComponent(jLabel2)
                                                            .addComponent(
                                                                txtFirstName,
                                                                GroupLayout.PREFERRED_SIZE,
                                                                GroupLayout.DEFAULT_SIZE,
                                                                GroupLayout.PREFERRED_SIZE))
                                                    .addGap(44, 44, 44)
                                                    .addComponent(jLabel3))
                                            .addComponent(
                                                txtLastName,
                                                GroupLayout.PREFERRED_SIZE,
                                                GroupLayout.DEFAULT_SIZE,
                                                GroupLayout.PREFERRED_SIZE))
                                    .addGap(49, 49, 49)
                                    .addComponent(jLabel4))
                            .addComponent(
                                txtUsername,
                                GroupLayout.PREFERRED_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE))
                    .addGap(46, 46, 46)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(
                                txtPassword,
                                GroupLayout.PREFERRED_SIZE,
                                GroupLayout.DEFAULT_SIZE,
                                GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(
                                jButton1,
                                GroupLayout.PREFERRED_SIZE,
                                48,
                                GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                jButton2,
                                GroupLayout.PREFERRED_SIZE,
                                44,
                                GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()));

    GroupLayout layout = new GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(
                        jPanel1,
                        GroupLayout.PREFERRED_SIZE,
                        GroupLayout.DEFAULT_SIZE,
                        GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(22, Short.MAX_VALUE)));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(
                layout
                    .createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(
                        jPanel1,
                        GroupLayout.PREFERRED_SIZE,
                        GroupLayout.DEFAULT_SIZE,
                        GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(14, Short.MAX_VALUE)));
    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed() { // GEN-FIRST:event_jButton1ActionPerformed
    // TODO add your handling code here:

    String ID = txtUserID.getText();
    String firstName = txtFirstName.getText();
    String lastName = txtLastName.getText();
    String username = txtUsername.getText();
    String password = txtPassword.getText();

    try {
      Class.forName("com.mysql.cj.jdbc.Driver");
      connection =
          DriverManager.getConnection("jdbc:mysql://localhost/airline", "root", "password");
      preparedStatement =
          connection.prepareStatement(
              "INSERT INTO USER (ID, firstName, lastName, username, password) VALUES (?, ?, ?, ?, ?)");

      preparedStatement.setString(1, ID);
      preparedStatement.setString(2, firstName);
      preparedStatement.setString(3, lastName);
      preparedStatement.setString(4, username);
      preparedStatement.setString(5, password);
      preparedStatement.executeUpdate();

      JOptionPane.showMessageDialog(null, "User Created.........");
    } catch (ClassNotFoundException | SQLException ex) {
      Logger.getLogger(addFlight.class.getName()).log(Level.SEVERE, null, ex);
    }
  } // GEN-LAST:event_jButton1ActionPerformed

  private void jButton2ActionPerformed() { // GEN-FIRST:event_jButton2ActionPerformed
    // TODO add your handling code here:
    this.hide();
  } // GEN-LAST:event_jButton2ActionPerformed

  public void autoID() {
    try {
      Class.forName("com.mysql.cj.jdbc.Driver");
      connection =
          DriverManager.getConnection("jdbc:mysql://localhost/airline", "root", "password");
      Statement statement = connection.createStatement();
      ResultSet resultSet = statement.executeQuery("SELECT MAX(ID) FROM USER");
      resultSet.next();
      resultSet.getString("MAX(ID)");
      if (resultSet.getString("MAX(ID)") == null) {
        txtUserID.setText("UO001");
      } else {
        long ID = Long.parseLong(resultSet.getString("MAX(ID)").substring(2));
        ID++;
        txtUserID.setText("UO" + String.format("%03d", ID));
      }

    } catch (ClassNotFoundException | SQLException ex) {
      Logger.getLogger(addCustomer.class.getName()).log(Level.SEVERE, null, ex);
    }
  }

  private JTextField txtFirstName;
  private JTextField txtLastName;
  private JPasswordField txtPassword;
  private JLabel txtUserID;
  private JTextField txtUsername;
  // End of variables declaration//GEN-END:variables
}
